# Generated by Django 3.1.3 on 2020-11-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='purchase',
            new_name='purchased',
        ),
    ]
